Quiz:
  tableName: quiz
  actAs:
    I18n:
      fields: [title, description]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    nome:
      type: string(50)
      notnull: false
    description:
      type: string(2147483647)
      notnull: true
QuizQuestions:
  tableName: quiz_questions
  actAs:
    Timestampable:
      created:
        name: created_at
        type: timestamp
        format: Y-m-d H:i:s
        options:
          notnull: true
      updated:
        name: updated_at
        type: timestamp
        format: Y-m-d H:i:s
        options:
          notnull: true
    I18n:
      fields: [question]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    quiz_id:
      type: integer(4)
    question:
      type: string(2147483647)
      notnull: true
    type_response:
      type: enum(8)
      values: ['single', 'multiple']
      default: 'single'
      notnull: true
    immagine:
      type: string(50)
      notnull: true
    topics_id: integer(1)
  relations:
    Quiz:
      local: quiz_id
      foreign: id
      type: one
    Topics:
      local: topics_id
      foreign: id
      type: one
QuizAnswers:
  tableName: quiz_answers
  actAs:
    Timestampable:
      created:
        name: created_at
        type: timestamp
        format: Y-m-d H:i:s
        options:
          notnull: true
      updated:
        name: updated_at
        type: timestamp
        format: Y-m-d H:i:s
        options:
          notnull: true
    I18n:
      fields: [answer, comment]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    quiz_questions_id:
      type: integer(4)
      default: '0'
      notnull: true
    answer:
      type: string(2147483647)
      notnull: true
    correct:
      type: boolean
      default: false
      notnull: true
    comment: string(2147483647)
  relations:
    QuizQuestions:
      local: quiz_questions_id
      foreign: id
      type: one